---
- name: Start Services Based on Server Role
  hosts: all
  gather_facts: yes

  tasks:
    - name: Include role-specific variables
      include_vars: "{{ playbook_dir }}/vars/{{ group_names[0] }}_vars.yaml"

    - name: Show the group(s) the server belongs to
      debug:
        msg: "The server '{{ inventory_hostname }}' belongs to the group(s): {{ group_names }}"

    - name: Get systemd service facts
      service_facts:

    - name: Start services based on the server's role
      systemd:
        name: "{{ item }}"
        state: started
      loop: "{{ services_to_start }}"
      when: item in ansible_facts.services and ansible_facts.services[item]['state'] == 'inactive'

