---
- name: Stop services based on hostname
  hosts: all
  gather_facts: false
  become: yes
  vars:
    service_mapping:
      proxy:
        - keepalived
        - haproxy
      proxhost:
        - cron
        - chrony
      pihole:
        - cron
        - chrony
      systools:
        - cron
        - chrony

  tasks:
    - name: Stop services in proper sequence
      block:
        - name: Stop services for each group
          service:
            name: "{{ item }}"
            state: stopped
          loop: "{{ service_mapping[ansible_hostname.split('.')[0]] }}"
          notify: confirm_service_stopped
      loop_control:
        pause: 30

  handlers:
    - name: confirm_service_stopped
      pause:
        prompt: "Confirm that service '{{ item }}' is stopped before proceeding (press Enter when done)"
        seconds: 30

