---
- name: Stop Services Based on Server Role
  hosts: all
  gather_facts: yes

  vars:
    service_mapping:
      webserver:
        - nginx
        - php
        - ntp
      dbserver:
        - ntp
      management:
        - mysql

  tasks:
    - name: Stop Apps
      systemd:
        state: stopped
        name: "{{ item }}"
      when: "inventory_hostname in service_mapping.keys()"
      loop: "{{ service_mapping[inventory_hostname] }}"
