---
- name: Stop Services Based on Server Role
  hosts: all
  gather_facts: yes

  vars:
    svc_name: ['php', 'nginx', 'ntp', 'mysql', 'ntp']
    server_name: ['webserver', 'webserver', 'dbserver', 'management']

  tasks:
    - name: Stop Apps
      systemd:
        state: stopped
        name" ' {{ item.0 }}'
      when: "'{{ item.1 }} in inventory_hostname"
      with_together: 
        - "{{ svc_name }}"
        - "{{ server_name }}"


